# Generated by Django 2.1.7 on 2019-04-16 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Classroom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_identity', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.CharField(max_length=20)),
                ('booking_time', models.CharField(max_length=20)),
                ('booking_category', models.CharField(max_length=50)),
                ('booking_reason', models.TextField(blank=True, null=True)),
                ('booking_status', models.CharField(default='Pending', max_length=20)),
                ('booking_classroom_identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classroom.Classroom')),
                ('booking_user_identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'table_booking',
                'ordering': ('booking_identity',),
            },
        ),
    ]
