# Generated by Django 2.1.7 on 2019-04-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('classroom_identity', models.AutoField(primary_key=True, serialize=False)),
                ('classroom_name', models.CharField(max_length=100)),
                ('classroom_capacity', models.IntegerField(null=True)),
                ('classroom_status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'table_classroom',
                'ordering': ('classroom_identity',),
            },
        ),
    ]
